import random


class Movies:

    """
    a class to set and get details of movies
    Attribute: title, year, genre, release_date and a 
    randomly generated ID for each movie
    Methods: a set method for each of the attributes except for 
    the random ID which is generated by importing the python random  module
             a get method for each of the attributes except for 
    the random ID which is generated by importing the python random  module
    """

    def __init__(self, title, year, genre, release_date, random_id=None):
        self.title = title
        self.year = year
        self.genre = genre
        self.release_date = release_date
        if random_id is None:
            random_id = random.randint(1000, 1999)
        self.random_id = random_id

        """
    a constructor of the movies class 
    to create an object of each attribute
    The random ID was set to None and with a conditional statement,
    the random function was passed to it and it's object was created
    """

    def set_title(self, title):
        self.title = title

    """
    a method to set title
    """

    def set_year(self, year):
        self.year = year

    """
    a method to set year
    """

    def set_genre(self, genre):
        self.genre = genre
    """
    a method to set genre
    """

    def set_release_date(self, release_date):
        self.release_date = release_date

    """
    a method to set release_date
    """

    def get_title(self):
        return self.title

    """
    a method to retrieve title
    """

    def get_year(self):
        return self.year

    """
    a method to retrieve year
    """
    def get_genre(self):
        return self.genre

    """
    a method to retrieve genre
    """

    def get_release_date(self):
        return self.release_date
    """
    a method to retrieve release date
    
    """



